# Generated by Django 4.2.1 on 2023-05-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_filiere_parent_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('groupe', models.CharField(max_length=3)),
                ('niveau', models.CharField(max_length=15)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.parent')),
            ],
        ),
    ]
