# Generated by Django 4.2.1 on 2023-05-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_etudiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
