# Generated by Django 4.2.1 on 2023-05-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCour', models.CharField(max_length=30)),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSalle', models.CharField(max_length=4)),
                ('etage', models.IntegerField()),
                ('TypeSalle', models.CharField(max_length=10)),
            ],
        ),
    ]
