# Generated by Django 4.2.1 on 2023-05-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_salle_salle_cour_presence_cour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='father',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='presence_cour',
            name='cour',
        ),
        migrations.RemoveField(
            model_name='presence_cour',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.RemoveField(
            model_name='salle_cour',
            name='cour',
        ),
        migrations.RemoveField(
            model_name='salle_cour',
            name='salle',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='Cour',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Filiere',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Presence_Cour',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Salle_Cour',
        ),
    ]
