# Generated by Django 4.1.7 on 2023-05-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
